"""IEC-ALP-IF-001 Rev A: terminal point data of the power island, as re-issued by IEC after TQ-IEC-021 (case-authoring aid).

One dict per interface; used by iec_docs.py to render the Rev A document and by the case loader to put the same values in
the database (so the vendor document and the records cannot diverge). Pressures barg (converted from IEC's bar(a) with
1.013 bar), temperatures degC. Fictional data."""

BARA = 1.013


def g(bara):
    return round(bara - BARA, 1)


E = "EPC"
I = "IEC"

# dates from the EPC level-1 commissioning sequence (key dates KD-010 back-feed 2028-08-02, KD-020 first fire 2028-10-02)
D_HV = ("2028-07-29", "2028-08-02")
D_AUX = ("2028-08-09", "2028-08-16")
D_WATER = ("2028-09-01", "2028-09-15")
D_STEAM = ("2028-09-30", "2028-10-16")
D_LDO = ("2028-11-15", "2028-12-01")

IF = {
    "IF-01": dict(category="process", size="12 in (DN300) CL600", connection="ASME B16.5 CL600 RF weld-neck flange",
                  boundary="IEC supplies the performance gas heater inlet flange; EPC supplies the counter-flange, gasket (spiral "
                           "wound, 316L/graphite), stud bolts and the pipe support nearest the flange, and makes the joint. "
                           "Hydrotest up to the flange by each party; joint leak test with gas-in by EPC.",
                  isolation="EPC: gas station outlet ESD valve (fail-closed, SIL 2, closed by the TCS gas trip) and manual valve "
                            "with spectacle blind upstream of IF-01. IEC: gas skid stop and control valves.",
                  protection="EPC gas station pressure control: monitor + active regulator, slam-shut set 46 barg, token relief "
                             "44 barg; downstream design 63 barg (EN 12186 / ASME B31.8).",
                  metering="Fiscal metering (ultrasonic 2 x 100 % + gas chromatograph) in the EPC gas station; IEC skid flow "
                           "meter for control only.",
                  design_pressure=63.0, design_temperature=80.0, operating_pressure_min=36.5, operating_pressure_max=41.0,
                  operating_temperature_min=5.0, operating_temperature_max=40.0, flow_normal=20.67, flow_max=23.0,
                  flow_unit="kg/s", hmb_stream=2, upstream="TP-G1", chain_dp=4.7, dates=("2028-08-31", "2028-09-18"),
                  cond="Pressure rate of change <= 0.7 bar/s; >= 28 K superheat above hydrocarbon and water dew points; "
                       "filtration 3 um absolute; below 36.5 barg the TCS load limiter applies (DEC-EPCE-0003)."),
    "IF-02": dict(category="process", size="6 in (DN150) CL150", connection="ASME B16.5 CL150 RF flange",
                  boundary="IEC supplies the liquid fuel skid inlet flange; EPC supplies counter-flange, gasket, bolts, the "
                           "last pipe support and the joint.",
                  isolation="EPC: LDO ESD valve (fail-closed) and manual valve with spectacle blind at the skid boundary. IEC: "
                            "skid stop valve.",
                  protection="EPC forwarding pumps: discharge relief to tank set 12 barg (< 16 barg design).",
                  metering="EPC Coriolis meter on the forwarding skid (consumption and performance tests).",
                  design_pressure=16.0, design_temperature=60.0, operating_pressure_min=3.0, operating_pressure_max=6.0,
                  operating_temperature_min=10.0, operating_temperature_max=45.0, flow_normal=22.41, flow_max=24.0,
                  flow_unit="kg/s", hmb_stream=27, dates=D_LDO,
                  cond="LDO treated by the EPC to the GT inlet limits (ER-03.07); filtration 5 um."),
    "IF-03": dict(category="process", size="4 in (DN100) CL150", connection="ASME B16.5 CL150 RF flange",
                  boundary="IEC supplies the water injection skid inlet flange (skid with high-pressure pumps by IEC); EPC "
                           "supplies counter-flange, gasket, bolts and the demin water forwarding pumps.",
                  isolation="EPC manual isolation valve and spectacle blind; IEC skid inlet valve.",
                  protection="EPC demin forwarding pumps shut-off head <= 12 barg (< 16 barg design).",
                  design_pressure=16.0, design_temperature=50.0, operating_pressure_min=3.0, operating_pressure_max=6.0,
                  operating_temperature_min=10.0, operating_temperature_max=40.0, flow_normal=13.44, flow_max=15.0,
                  flow_unit="kg/s", hmb_stream=28, hmb_check="flow_temperature", dates=D_LDO,
                  cond="Water/fuel ratio 0.60 on LDO (TQ-IEC-018). HMB stream 28 is at the IEC skid discharge (60 bar(a)); "
                       "pressure at IF-03 is 3.0-6.0 barg.",
                  remarks="HMB pressure check not applicable: PER-003 stream 28 is downstream of the IEC injection pumps "
                          "(TQ-IEC-021 item 3); the injection pump power is part of the IEC GT auxiliaries."),
    "IF-04": dict(category="utility", size="2 in (DN50) CL150", connection="ASME B16.5 CL150 RF flange",
                  boundary="IEC wash skid inlet flange; EPC demin water line, counter-flange, gasket and bolts.",
                  isolation="EPC manual valve; IEC skid inlet valve.", protection="EPC demin pumps shut-off <= 8 barg.",
                  design_pressure=10.0, design_temperature=50.0, operating_pressure_min=3.0, operating_pressure_max=6.0,
                  operating_temperature_min=10.0, operating_temperature_max=40.0, flow_normal=5.0, flow_max=10.0,
                  flow_unit="m3/h", density=1000.0, dates=("2028-09-15", "2028-12-15"),
                  cond="5 m3 per wash (off-line), tank filling at up to 10 m3/h."),
    "IF-05": dict(category="process", size="12 in P91 (SA-335 P91)", connection="butt-weld end ASME B16.25, IEC pup piece 300 mm",
                  boundary="IEC supplies the HP SH outlet stop valve with a 300 mm pup piece (matching material and wall); the "
                           "field weld, its PWHT and 100 % RT/UT are by EPC, witnessed by IEC.",
                  isolation="IEC HP SH outlet motor-operated stop valve and non-return valve.",
                  protection="IEC HRSG HP SH safety valves set <= 196 bar(a), electromatic relief 194 bar(a).",
                  design_pressure=g(210), design_temperature=610.0, operating_pressure_min=59.0, operating_pressure_max=192.0,
                  operating_temperature_min=560.0, operating_temperature_max=600.0, flow_normal=100.16, flow_max=105.0,
                  flow_unit="kg/s", hmb_stream=6, dates=D_STEAM,
                  cond="Sliding pressure 60-193 bar(a); attemperation to 600 degC."),
    "IF-06": dict(category="process", size="12 in P91 (SA-335 P91)", connection="butt-weld end ASME B16.25, IEC pup piece 300 mm",
                  boundary="IEC supplies the ST main stop valve with pup piece; field weld, PWHT and NDT by EPC.",
                  isolation="IEC main stop valve (ST trip).",
                  protection="Upstream HRSG HP SH safety valves (IF-05) <= 196 bar(a); MSV casing design 215 bar(a) / 610 degC "
                             "(TQ-IEC-021 item 1).",
                  design_pressure=g(215), design_temperature=610.0, operating_pressure_min=52.0, operating_pressure_max=186.0,
                  operating_temperature_min=560.0, operating_temperature_max=600.0, flow_normal=100.16, flow_max=105.0,
                  flow_unit="kg/s", hmb_stream=7, upstream="IF-05", chain_dp=6.0, dates=D_STEAM,
                  cond="ST rated inlet 180 bar(a) / 598 degC per IEC 60045-1; main steam line pressure drop <= 6.0 bar at 105 kg/s."),
    "IF-07": dict(category="process", size="24 in SA-335 P22", connection="butt-weld end, IEC pup piece",
                  boundary="IEC supplies the HP turbine exhaust nozzle with pup piece and the CRH non-return valve; field weld "
                           "by EPC.",
                  isolation="IEC CRH non-return valve (power assisted).", protection="Reheater safety valves on the HRSG (IEC).",
                  design_pressure=g(52), design_temperature=420.0, operating_pressure_min=18.0, operating_pressure_max=41.0,
                  operating_temperature_min=340.0, operating_temperature_max=395.0, flow_normal=100.16, flow_max=105.0,
                  flow_unit="kg/s", hmb_stream=8, dates=D_STEAM),
    "IF-08": dict(category="process", size="24 in SA-335 P22", connection="butt-weld end, IEC pup piece",
                  boundary="IEC supplies the HRSG reheater inlet with pup piece and the CRH safety valves; field weld by EPC.",
                  isolation="None at the HRSG inlet (CRH non-return valve at IF-07).",
                  protection="IEC cold reheat safety valves set 50 bar(a).",
                  design_pressure=g(52), design_temperature=420.0, operating_pressure_min=17.0, operating_pressure_max=41.0,
                  operating_temperature_min=340.0, operating_temperature_max=395.0, flow_normal=100.16, flow_max=105.0,
                  flow_unit="kg/s", hmb_stream=9, upstream="IF-07", chain_dp=1.0, dates=D_STEAM),
    "IF-09": dict(category="process", size="28 in P91 (SA-335 P91)", connection="butt-weld end, IEC pup piece",
                  boundary="IEC supplies the HRSG reheater outlet stop valve with pup piece; field weld, PWHT, NDT by EPC.",
                  isolation="IEC HRH outlet stop valve.", protection="IEC hot reheat safety valves set <= 48 bar(a).",
                  design_pressure=g(50), design_temperature=610.0, operating_pressure_min=17.0, operating_pressure_max=38.5,
                  operating_temperature_min=550.0, operating_temperature_max=600.0, flow_normal=117.5, flow_max=125.0,
                  flow_unit="kg/s", hmb_stream=11, dates=D_STEAM),
    "IF-10": dict(category="process", size="28 in P91 (SA-335 P91)", connection="butt-weld end, IEC pup piece",
                  boundary="IEC supplies the ST IP stop/control valve with pup piece; field weld, PWHT, NDT by EPC.",
                  isolation="IEC IP stop valve (ST trip).",
                  protection="Upstream HRH safety valves (IF-09) <= 48 bar(a); IP valve casing design 52 bar(a) / 610 degC "
                             "(TQ-IEC-021 item 1).",
                  design_pressure=g(52), design_temperature=610.0, operating_pressure_min=15.5, operating_pressure_max=38.5,
                  operating_temperature_min=550.0, operating_temperature_max=600.0, flow_normal=117.5, flow_max=125.0,
                  flow_unit="kg/s", hmb_stream=12, upstream="IF-09", chain_dp=1.5, dates=D_STEAM),
    "IF-11": dict(category="process", size="20 in SA-106 C", connection="butt-weld end",
                  boundary="IEC supplies the LP SH outlet stop valve with pup piece; field weld by EPC.",
                  isolation="IEC LP SH outlet stop valve and non-return valve.", protection="IEC LP SH safety valve set 8.0 bar(a).",
                  design_pressure=g(10), design_temperature=330.0, operating_pressure_min=1.5, operating_pressure_max=5.0,
                  operating_temperature_min=210.0, operating_temperature_max=260.0, flow_normal=11.39, flow_max=16.5,
                  flow_unit="kg/s", hmb_stream=13, dates=D_STEAM),
    "IF-12": dict(category="process", size="20 in SA-106 C", connection="butt-weld end",
                  boundary="IEC supplies the ST LP admission valve with pup piece; field weld by EPC.",
                  isolation="IEC LP admission stop valve.",
                  protection="Upstream LP SH safety valve (IF-11) 8.0 bar(a); admission valve casing design 10 bar(a) / 330 "
                             "degC (TQ-IEC-021 item 1).",
                  design_pressure=g(10), design_temperature=330.0, operating_pressure_min=1.1, operating_pressure_max=5.0,
                  operating_temperature_min=210.0, operating_temperature_max=260.0, flow_normal=11.39, flow_max=16.5,
                  flow_unit="kg/s", hmb_stream=14, upstream="IF-11", chain_dp=0.4, dates=D_STEAM),
    "IF-13": dict(category="process", size="HP 12 in / IP 28 in / LP 20 in (per valve datasheets)",
                  connection="butt-weld ends; spray water flanges CL2500 (HP) / CL600 (IP, LP)",
                  boundary="Loose supply: IEC supplies HP, IP and LP bypass valves with desuperheaters (free issue to site); "
                           "EPC installs them in its piping, supplies the spray water lines from the BFP discharge/interstage "
                           "and CEP discharge and all welds.",
                  isolation="EPC isolation on the spray water lines; bypass valves close on loss of spray water (IEC logic).",
                  protection="HP bypass downstream design 52 bar(a) (CRH); IP/LP bypass downstream 16 bar(a) (IF-14).",
                  design_pressure=g(215), design_temperature=610.0, operating_pressure_min=1.0, operating_pressure_max=192.0,
                  operating_temperature_min=150.0, operating_temperature_max=600.0, flow_max=125.0, flow_unit="kg/s",
                  dates=("2028-02-01", "2028-03-01"),
                  cond="Inlet side most onerous (HP bypass inlet); delivery of the loose valves by 2028-02-01 for piping erection."),
    "IF-14": dict(category="process", size="2 x 36 in + 1 x 28 in", connection="butt-weld end at the condenser neck dump devices",
                  boundary="IEC supplies the dump devices in the condenser neck with weld ends; EPC supplies the IP/LP bypass "
                           "downstream piping and the welds.",
                  isolation="Bypass valves (IF-13).", protection="Condenser rupture discs (IEC) and bypass trip on high condenser pressure.",
                  design_pressure=g(16), design_temperature=250.0, operating_pressure_min=-1.0, operating_pressure_max=12.0,
                  operating_temperature_min=40.0, operating_temperature_max=250.0, flow_max=141.5, flow_unit="kg/s",
                  dates=("2028-05-01", "2028-06-01"), cond="Start-up and trip only; 100 % HRH + LP flow."),
    "IF-15": dict(category="process", size="20 in (DN500) CL150", connection="ASME B16.5 CL150 RF flange, vacuum-tight",
                  boundary="IEC hotwell outlet nozzle flange; EPC counter-flange, spiral-wound gasket, bolts and CEP suction piping.",
                  isolation="EPC motor-operated suction valve per CEP.", protection="Full vacuum design both sides.",
                  design_pressure=g(3.5), design_temperature=80.0, operating_pressure_min=-0.995, operating_pressure_max=-0.9,
                  operating_temperature_min=15.0, operating_temperature_max=40.0, flow_normal=128.0, flow_max=140.0,
                  flow_unit="kg/s", hmb_stream=17, dates=D_WATER, cond="Full vacuum to 3.5 bar(a)."),
    "IF-16": dict(category="process", size="12 in (DN300) CL300", connection="ASME B16.5 CL300 RF flange",
                  boundary="IEC HRSG condensate preheater inlet flange; EPC condensate line, counter-flange, gasket, bolts.",
                  isolation="EPC motor-operated isolation valve.",
                  protection="EPC CEP shut-off head <= 22 bar(a) at maximum speed (< 25 bar(a) design), verified at pump FAT.",
                  design_pressure=g(25), design_temperature=180.0, operating_pressure_min=12.0, operating_pressure_max=21.0,
                  operating_temperature_min=15.0, operating_temperature_max=45.0, flow_normal=141.37, flow_max=150.0,
                  flow_unit="kg/s", hmb_stream=20, dates=D_WATER),
    "IF-17": dict(category="process", size="16 in (DN400) CL150", connection="ASME B16.5 CL150 RF flange",
                  boundary="IEC LP drum downcomer outlet nozzle flange; EPC BFP suction piping, counter-flange, gasket, bolts.",
                  isolation="EPC suction isolation valve per BFP.", protection="IEC LP drum safety valves.",
                  design_pressure=g(10), design_temperature=185.0, operating_pressure_min=1.5, operating_pressure_max=6.0,
                  operating_temperature_min=130.0, operating_temperature_max=165.0, flow_normal=129.98, flow_max=140.0,
                  flow_unit="kg/s", hmb_stream=21, dates=D_WATER,
                  cond="LP drum normal water level EL +31.5 m; the EPC confirms BFP NPSH with the drum level and suction losses."),
    "IF-18": dict(category="process", size="10 in (DN250) CL2500", connection="butt-weld end (SA-106 C / SA-335 P11)",
                  boundary="IEC HRSG HP economiser 1 inlet with pup piece; field weld by EPC.",
                  isolation="EPC HP feedwater motor-operated isolation valve and non-return valve.",
                  protection="EPC BFP shut-off head at maximum speed <= 234 barg (VFD speed limit), verified at pump FAT; "
                             "minimum-flow recirculation valve.",
                  design_pressure=g(235), design_temperature=200.0, operating_pressure_min=95.0, operating_pressure_max=215.0,
                  operating_temperature_min=130.0, operating_temperature_max=170.0, flow_normal=100.16, flow_max=110.0,
                  flow_unit="kg/s", hmb_stream=22, dates=D_WATER),
    "IF-19": dict(category="process", size="6 in (DN150) CL600", connection="butt-weld end",
                  boundary="IEC HRSG IP economiser inlet with pup piece; field weld by EPC.",
                  isolation="EPC IP feedwater isolation and non-return valve.",
                  protection="EPC BFP interstage pressure at shut-off <= 58 bar(a), verified at FAT.",
                  design_pressure=g(60), design_temperature=200.0, operating_pressure_min=20.0, operating_pressure_max=48.0,
                  operating_temperature_min=130.0, operating_temperature_max=165.0, flow_normal=29.82, flow_max=33.0,
                  flow_unit="kg/s", hmb_stream=23, dates=D_WATER),
    "IF-20": dict(category="process", size="4 in (DN100) CL600", connection="ASME B16.5 CL600 RF flange",
                  boundary="IEC performance gas heater water outlet flange; EPC return line to the condensate system.",
                  isolation="EPC isolation valve; IEC FGH outlet control valve.",
                  protection="EPC return line designed 60 bar(a) / 260 degC up to and including its pressure-reducing valve at "
                             "the condensate connection; condensate system relief valve downstream (EPC).",
                  design_pressure=g(60), design_temperature=260.0, operating_pressure_min=18.0, operating_pressure_max=46.0,
                  operating_temperature_min=60.0, operating_temperature_max=90.0, flow_normal=12.48, flow_max=14.5,
                  flow_unit="kg/s", hmb_stream=19, dates=D_WATER),
    "IF-21": dict(category="process", size="2 in / 3 in", connection="socket-weld / butt-weld ends",
                  boundary="IEC supplies the continuous and intermittent blowdown valves (two in series); scope break at the "
                           "outlet weld of the second valve; EPC blowdown piping, flash tanks and silencers.",
                  isolation="IEC two valves in series (ASME I PG-58.3.6).",
                  protection="EPC blowdown piping designed for the drum design pressure up to the flash tank inlet.",
                  design_pressure=g(210), design_temperature=370.0, operating_pressure_min=0.0, operating_pressure_max=5.0,
                  operating_temperature_min=100.0, operating_temperature_max=370.0, flow_normal=1.0, flow_max=5.0,
                  flow_unit="kg/s", dates=D_WATER, cond="Continuous blowdown up to 1 % of HP flow; intermittent 5 kg/s for 30 s."),
    "IF-22": dict(category="process", size="various (1 in - 3 in)", connection="socket-weld / butt-weld ends",
                  boundary="Scope break at the outlet weld of the IEC drain/vent valve (second isolation); EPC drain collection, "
                           "atmospheric flash tanks and vent silencers.",
                  isolation="IEC two valves in series on all pressure part drains.",
                  protection="EPC drain headers designed for the highest upstream design up to the first flash tank.",
                  design_pressure=g(210), design_temperature=610.0, operating_pressure_min=0.0, operating_pressure_max=1.0,
                  operating_temperature_min=40.0, operating_temperature_max=610.0, flow_max=10.0, flow_unit="kg/s",
                  dates=D_WATER, cond="Start-up drains."),
    "IF-23": dict(category="utility", size="1 in", connection="socket-weld, IEC root valve",
                  boundary="IEC dosing nozzles with root valves on the drums; EPC dosing skids and lines.",
                  isolation="IEC root valve + EPC isolation and check valve.",
                  protection="EPC dosing pump relief set below the line design.",
                  design_pressure=g(235), design_temperature=100.0, operating_pressure_min=3.0, operating_pressure_max=215.0,
                  operating_temperature_min=5.0, operating_temperature_max=40.0, flow_max=0.1, flow_unit="m3/h",
                  density=1000.0, dates=D_WATER, cond="Lay-up and optional drum dosing; AVT(O) ammonia dosing into the "
                                                       "condensate by EPC."),
    "IF-24": dict(category="utility", size="1/2 in", connection="socket-weld, IEC root valve",
                  boundary="IEC sample nozzles with root valves; EPC sample lines, coolers and the SWAS.",
                  isolation="IEC root valve; EPC isolation at the SWAS.", protection="EPC sample line design = upstream design.",
                  design_pressure=g(235), design_temperature=610.0, operating_pressure_min=-1.0, operating_pressure_max=215.0,
                  operating_temperature_min=20.0, operating_temperature_max=600.0, flow_max=0.5, flow_unit="kg/s",
                  dates=D_WATER, cond="Sample points per IEC-ALP-REQ-001 section 4."),
    "IF-25": dict(category="utility", size="1 in", connection="ASME B16.5 CL150 RF flange (316L)",
                  boundary="IEC ammonia injection skid inlet flange; EPC storage, unloading and forwarding pumps.",
                  isolation="EPC ESD valve (fail-closed) and manual valve.", protection="EPC forwarding pump relief 9 barg.",
                  design_pressure=10.0, design_temperature=40.0, operating_pressure_min=3.0, operating_pressure_max=7.0,
                  operating_temperature_min=5.0, operating_temperature_max=40.0, flow_normal=0.125, flow_max=0.5,
                  flow_unit="t/h", dates=("2028-11-01", "2028-11-15"),
                  cond="Aqueous ammonia 24.5 %: 125 kg/h on gas, 480 kg/h on LDO (TQ-IEC-018)."),
    "IF-26": dict(category="process", size="D 9.2 m", connection="bolted flange with EPC fabric expansion joint",
                  boundary="IEC HRSG outlet transition duct flange (drilled); EPC fabric expansion joint, stack, silencer, "
                           "CEMS and damper (if any).",
                  isolation="None (no stack damper).", protection="HRSG casing design +/- 50 mbar.",
                  design_pressure=0.05, design_temperature=200.0, operating_pressure_min=0.0, operating_pressure_max=0.03,
                  operating_temperature_min=60.0, operating_temperature_max=120.0, flow_normal=796.7, flow_max=850.0,
                  flow_unit="kg/s", hmb_stream=5, dates=("2028-06-30", "2028-09-15")),
    "IF-27": dict(category="process", size="4 x DN1800", connection="EN 1092-1 PN6 flanges, rubber-lined water boxes",
                  boundary="IEC condenser water box inlet/outlet flanges; EPC CW piping (GRP), expansion joints, counter-flanges "
                           "and bolts.",
                  isolation="EPC butterfly valves per inlet and outlet half (condenser half-side operation).",
                  protection="EPC CW pump shut-off head <= 3.5 barg at the condenser; surge analysis for pump trip <= 4 barg; "
                             "vacuum breaker at the outlet high point.",
                  design_pressure=4.0, design_temperature=40.0, operating_pressure_min=0.5, operating_pressure_max=3.0,
                  operating_temperature_min=5.0, operating_temperature_max=35.0, flow_normal=36050.0, flow_max=38000.0,
                  flow_unit="m3/h", density=1025.0, hmb_stream=25, dates=D_WATER,
                  cond="Design flow 38,000 m3/h (DEC-EPCE-0002); condenser pressure drop 0.62 bar clean."),
    "IF-28": dict(category="utility", size="various (DN50 - DN400)", connection="ASME B16.5 CL150 RF flanges",
                  boundary="IEC cooler inlet/outlet flanges; EPC CCW system.", isolation="EPC valves per consumer.",
                  protection="EPC CCW pump shut-off <= 8 barg.", design_pressure=10.0, design_temperature=60.0,
                  operating_pressure_min=3.0, operating_pressure_max=6.0, operating_temperature_min=20.0,
                  operating_temperature_max=36.0, flow_normal=1055.0, flow_max=1160.0, flow_unit="m3/h", density=1000.0,
                  dates=D_AUX, cond="9,400 kW; supply <= 36 degC (ST TEWAC) / 38 degC (others)."),
    "IF-29": dict(category="utility", size="1 in - 2 in", connection="ASME B16.5 CL150 RF flanges",
                  boundary="IEC skid inlet flanges; EPC compressed air system.", isolation="EPC valve per skid.",
                  protection="EPC air receivers relief 10 barg.", design_pressure=10.0, design_temperature=50.0,
                  operating_pressure_min=6.0, operating_pressure_max=8.0, operating_temperature_min=5.0,
                  operating_temperature_max=45.0, flow_normal=350.0, flow_max=500.0, flow_unit="Nm3/h", density=1.293,
                  dates=D_AUX, cond="Instrument air dew point -40 degC at 7 barg (ISO 8573-1 class 1.2.1)."),
    "IF-30": dict(category="utility", size="1 in", connection="ASME B16.5 CL150 RF flange",
                  boundary="IEC lay-up / purge connections; EPC nitrogen supply.", isolation="EPC valve + IEC valve.",
                  protection="EPC pressure regulator + relief 9 barg.", design_pressure=10.0, design_temperature=50.0,
                  operating_pressure_min=5.0, operating_pressure_max=8.0, operating_temperature_min=5.0,
                  operating_temperature_max=40.0, flow_max=1000.0, flow_unit="Nm3/h", density=1.25, dates=D_WATER,
                  cond="99.9 % N2; 3,000 Nm3 per lay-up event."),
    "IF-31": dict(category="utility", size="1/2 in", connection="compression fitting (316L)",
                  boundary="IEC generator gas control panel inlet; EPC bottle racks, regulators and piping.",
                  isolation="EPC valves at the racks.", protection="EPC regulator + relief 14 barg.",
                  design_pressure=16.0, design_temperature=50.0, operating_pressure_min=8.0, operating_pressure_max=12.0,
                  operating_temperature_min=5.0, operating_temperature_max=40.0, flow_max=60.0, flow_unit="Nm3/h",
                  dates=("2028-08-25", "2028-09-01"), cond="H2 99.9 %, 12 Nm3/day; CO2 150 Nm3 per purge."),
    "IF-32": dict(category="utility", size="4 in (DN100) CL300", connection="butt-weld end",
                  boundary="IEC gland steam header inlet; EPC auxiliary steam line from the auxiliary boiler.",
                  isolation="EPC isolation valve.", protection="EPC auxiliary steam header relief set 15 barg.",
                  design_pressure=g(16), design_temperature=320.0, operating_pressure_min=8.0, operating_pressure_max=9.5,
                  operating_temperature_min=250.0, operating_temperature_max=300.0, flow_normal=4.5, flow_max=7.5,
                  flow_unit="t/h", dates=("2028-09-30", "2028-10-16"), cond="4.5 t/h gland sealing, 3 t/h HRSG sparging (optional)."),
    "IF-33": dict(category="control", connection="hardwired volt-free contacts + Modbus TCP summary",
                  boundary="IEC GT enclosure CO2 fire protection panel terminals; EPC fire alarm panel (NFPA 72), cables, "
                           "transformer deluge, hydrants.",
                  isolation="-", dates=("2028-08-17", "2028-08-24")),
    "IF-34": dict(category="electrical", size="560 MVA", connection="GSU HV air bushings, EPC 420 kV connection to the GIS",
                  boundary="IEC GSU HV bushing terminals; EPC conductors/cable, clamps, surge arresters at the bushings and the "
                           "GIS bay.",
                  isolation="EPC GIS generator transformer bay circuit breaker, disconnector and earthing switch; IEC GCB on "
                            "the LV side.",
                  protection="GSU differential (87T) and overall differential (87G-T) by IEC; GIS bay protection by EPC; trip "
                             "matrix per IF-41.",
                  voltage_nominal=380.0, voltage_min=342.0, voltage_max=420.0, short_circuit=50.0, short_circuit_rating=50.0,
                  power_factor=0.85, flow_max=560.0, flow_unit="MVA", hmb_metric="gt_output", upstream="TP-E1", dates=D_HV,
                  cond="OLTC 400 +/- 8 x 1.25 % (360-440 kV) with generator 21 kV +/- 5 % covers 342-420 kV."),
    "IF-35": dict(category="electrical", size="270 MVA", connection="GSU HV air bushings, EPC 420 kV connection to the GIS",
                  boundary="As IF-34 for the ST GSU.", isolation="As IF-34.", protection="As IF-34.",
                  voltage_nominal=380.0, voltage_min=342.0, voltage_max=420.0, short_circuit=50.0, short_circuit_rating=50.0,
                  power_factor=0.85, flow_max=270.0, flow_unit="MVA", hmb_metric="st_output", upstream="TP-E1", dates=D_HV,
                  cond="OLTC 400 +/- 8 x 1.25 % with generator 15.75 kV +/- 5 %."),
    "IF-36": dict(category="electrical", size="21 kV (GT) / 15.75 kV (ST)", connection="IPB tap-off flange (IEC), EPC MV busduct",
                  boundary="IEC IPB tap-off flange between GCB and GSU; EPC UAT, UAT busduct and flexible links.",
                  isolation="IEC tap-off disconnector link; EPC UAT MV circuit breaker.",
                  protection="UAT differential and overcurrent by EPC, integrated in the IEC unit trip matrix.",
                  voltage_nominal=21.0, voltage_min=19.95, voltage_max=22.05, short_circuit=169.0,
                  short_circuit_rating=200.0, flow_max=31.5, flow_unit="MVA", dates=D_AUX,
                  cond="Prospective 169 kA at the GT generator bus (96 kA via GSU + 73 kA generator); ST bus 125 kA. "
                       "IPB tap-off rated 200 kA sym / 550 kA peak (TQ-IEC-021 item 4)."),
    "IF-37": dict(category="electrical", size="10.5 kV feeders", connection="cable terminations at the IEC equipment (lugs by EPC)",
                  boundary="EPC 10.5 kV feeders and cables up to and including the terminations at the IEC equipment.",
                  isolation="EPC feeder circuit breaker with earthing switch.", protection="EPC feeder protection.",
                  voltage_nominal=10.5, voltage_min=9.45, voltage_max=11.55, short_circuit=35.0, short_circuit_rating=40.0,
                  flow_max=10.0, flow_unit="MVA", dates=D_AUX, cond="SFC 8.5 MW for 30 min at start-up."),
    "IF-38": dict(category="electrical", size="0.4 kV feeders", connection="IEC MCC incoming terminals",
                  boundary="EPC 0.4 kV feeders and cables up to the IEC MCC incoming terminals.",
                  isolation="EPC feeder breaker; IEC MCC incomer.", protection="EPC feeder protection selective with IEC MCC.",
                  voltage_nominal=0.4, voltage_min=0.36, voltage_max=0.44, short_circuit=50.0, short_circuit_rating=50.0,
                  dates=D_AUX, cond="Loads per IEC-ALP-REQ-001 section 7.1."),
    "IF-39": dict(category="electrical", size="220 V DC / 230 V AC UPS", connection="IEC panel incoming terminals",
                  boundary="EPC DC and UPS distribution feeders up to the IEC panel terminals.",
                  isolation="EPC feeder MCB/fuse.", protection="EPC selective fusing.",
                  voltage_nominal=0.22, voltage_min=0.187, voltage_max=0.242, dates=D_AUX,
                  cond="GT 37 kW / ST 45 kW DC emergency oil pumps, 3 h autonomy; 45 kVA UPS for the TCS."),
    "IF-40": dict(category="control", connection="OPC UA + Modbus TCP, redundant fibre; hardwired trips",
                  boundary="IEC TCS gateway ports and fibre patch panel in the IEC electronic room; EPC fibre cables, DCS "
                           "and the firewall between the zones (IEC 62443 zone/conduit).",
                  isolation="-", dates=("2028-06-01", "2028-06-15"), cond="About 2,500 signals."),
    "IF-41": dict(category="control", connection="IEC 61850 (GOOSE/MMS) + hardwired trips",
                  boundary="IEC generator/GSU protection panel terminals; EPC switchyard protection, substation automation "
                           "and TSO SCADA.",
                  isolation="-", dates=D_HV),
    "IF-42": dict(category="civil", connection="bolted earthing pads (IEC), EPC 240 mm2 Cu risers",
                  boundary="IEC equipment earthing pads and internal earthing; EPC earthing grid (IEEE 80) and risers.",
                  isolation="-", dates=("2027-10-15", "2027-11-15")),
    "IF-43": dict(category="civil", connection="anchor bolts / sole plates (IEC supply), grout by EPC to IEC specification",
                  boundary="IEC load data, anchor bolts, sole plates and grouting specification; EPC foundation design, "
                           "construction, cast-in of anchor bolts and grouting.",
                  isolation="-", dates=("2027-11-01", "2027-11-15"), cond="Loads per IEC-ALP-REQ-001 section 9."),
    "IF-44": dict(category="process", size="2 x DN150 per inlet half", connection="EN 1092-1 PN10 flanges",
                  boundary="IEC ball injection nozzles on the condenser inlet water boxes; EPC tube cleaning system (ball "
                           "strainers in the outlet lines, recirculation pumps, collectors).",
                  isolation="EPC valves at the nozzles.", protection="As IF-27.", design_pressure=4.0, design_temperature=40.0,
                  operating_pressure_min=0.5, operating_pressure_max=3.5, operating_temperature_min=5.0,
                  operating_temperature_max=35.0, flow_max=200.0, flow_unit="m3/h", density=1025.0, dates=D_WATER),
    "IF-45": dict(category="process", size="3 in (DN80) CL2500", connection="butt-weld end",
                  boundary="IEC HP attemperator spray control station inlet (station with control and block valves by IEC); "
                           "EPC spray water line from the BFP discharge and the weld.",
                  isolation="EPC isolation valve at the BFP discharge header; IEC block valve.",
                  protection="As IF-18 (BFP shut-off <= 234 barg).", design_pressure=g(235), design_temperature=200.0,
                  operating_pressure_min=95.0, operating_pressure_max=215.0, operating_temperature_min=130.0,
                  operating_temperature_max=170.0, flow_max=5.0, flow_unit="kg/s", hmb_stream=29, dates=D_WATER,
                  service="HP attemperation spray water", medium="feedwater",
                  location_text="HRSG HP attemperator spray control station inlet",
                  owner_side="EPC: spray water line from the BFP discharge",
                  contractor_side="IEC: HP attemperator spray control station"),
    "IF-46": dict(category="process", size="2 in (DN50) CL600", connection="butt-weld end",
                  boundary="IEC reheat attemperator spray control station inlet; EPC spray water line from the BFP interstage.",
                  isolation="EPC isolation valve at the interstage header; IEC block valve.",
                  protection="As IF-19 (interstage <= 58 bar(a)).", design_pressure=g(60), design_temperature=200.0,
                  operating_pressure_min=20.0, operating_pressure_max=48.0, operating_temperature_min=130.0,
                  operating_temperature_max=170.0, flow_max=3.0, flow_unit="kg/s", hmb_stream=30, dates=D_WATER,
                  service="Reheat attemperation spray water", medium="feedwater",
                  location_text="HRSG reheat attemperator spray control station inlet",
                  owner_side="EPC: spray water line from the BFP interstage",
                  contractor_side="IEC: reheat attemperator spray control station"),
}
