"""Internal deliveries: frozen, committed copies of engine outputs with a transmittal.

internal_deliveries/<DLV-id>_<slug>/
    <copied output files>
    transmittal.json   files + sha256, source engine manifest, db hash, who, why
    TRANSMITTAL.md     human-readable cover sheet, rendered from transmittal.json
A `delivery` record is also created in the database so issues are queryable.
"""
from __future__ import annotations

import json
import re
import shutil
from pathlib import Path

from .project import Project
from .runner import MANIFEST, check_outputs, sha256
from .store import Store, now

TRANSMITTAL_JSON = "transmittal.json"
TRANSMITTAL_MD = "TRANSMITTAL.md"


def render_md(t: dict) -> str:
    lines = [f"# Transmittal {t['id']}", "",
             f"**Title:** {t['title']}  ", f"**Purpose:** {t['purpose']}  ", f"**To:** {t['recipients']}  ",
             f"**Issued by:** {t['issued_by']} on {t['issued_at'][:10]}  ",
             f"**Source engine:** {t['engine']} v{t['engine_version']} (generated {t['generated_at'][:19]}Z)  ",
             f"**Database fingerprint:** {t['db_hash']} / inputs {t['inputs_hash']}  ",
             f"**Git commit at generation:** {t['git_commit']}", "",
             f"**Remarks:** {t['remarks']}", "", "| File | SHA-256 (first 16) |", "|---|---|"]
    lines += [f"| {f} | {h[:16]} |" for f, h in sorted(t["files"].items())]
    lines += ["", "_Generated by `python -m engine deliver`. Do not edit - any change invalidates this transmittal._", ""]
    return "\n".join(lines)


def deliver(project: Project, store: Store, engine: str, title: str, purpose: str,
            recipients: str, reason: str, patterns: list[str] | None = None, revisions: list[str] | None = None) -> Path:
    src = project.output / engine
    mf = src / MANIFEST
    if not mf.exists():
        raise RuntimeError(f"no output for engine '{engine}'. Run: python -m engine run {engine}")
    problems = [m for lvl, m in check_outputs(project, store) if m.startswith(f"output/{engine}/")]
    if problems:
        raise RuntimeError("cannot deliver - output is not clean:\n" + "\n".join(problems))
    manifest = json.loads(mf.read_text(encoding="utf-8"))
    files = sorted(manifest["files"])
    if patterns:
        files = [f for f in files if any(Path(f).match(p) for p in patterns)]
    if not files:
        raise RuntimeError("no files selected for delivery")

    rid = store.next_id("delivery")
    slug = re.sub(r"[^A-Za-z0-9]+", "-", title).strip("-")[:40] or "delivery"
    dest = project.deliveries / f"{rid}_{slug}"
    dest.mkdir(parents=True)
    try:
        for f in files:
            (dest / f).parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src / f, dest / f)
        t = {"id": rid, "title": title, "purpose": purpose, "recipients": recipients, "remarks": reason,
             "issued_by": store.who.code, "issued_at": now(), "folder": project.rel(dest),
             "files": {f: sha256(dest / f) for f in files},
             **{k: manifest.get(k) for k in ("engine", "engine_version", "generated_at", "inputs_hash", "db_hash", "git_commit")}}
        (dest / TRANSMITTAL_JSON).write_text(json.dumps(t, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        (dest / TRANSMITTAL_MD).write_text(render_md(t), encoding="utf-8")
        store.create("delivery", {"id": rid, "title": title, "purpose": purpose, "recipients": recipients,
                                  "engine": engine, "folder": project.rel(dest), "file_count": len(files),
                                  "db_hash": manifest.get("db_hash"), **({"revisions": revisions} if revisions else {})},
                     reason)
    except Exception:
        shutil.rmtree(dest, ignore_errors=True)
        raise
    return dest


def check_deliveries(project: Project) -> list[str]:
    errs = []
    if not project.deliveries.is_dir():
        return errs
    for d in sorted(p for p in project.deliveries.iterdir() if p.is_dir()):
        tj = d / TRANSMITTAL_JSON
        where = f"internal_deliveries/{d.name}"
        if not tj.exists():
            errs.append(f"{where}: no transmittal.json - only `python -m engine deliver` may create deliveries")
            continue
        t = json.loads(tj.read_text(encoding="utf-8"))
        for f, h in t["files"].items():
            if not (d / f).exists():
                errs.append(f"{where}/{f}: missing")
            elif sha256(d / f) != h:
                errs.append(f"{where}/{f}: changed after issue - issued deliveries are frozen; issue a new one")
        md = d / TRANSMITTAL_MD
        if not md.exists() or md.read_text(encoding="utf-8") != render_md(t):
            errs.append(f"{where}/{TRANSMITTAL_MD}: missing or edited")
        extra = [p.relative_to(d).as_posix() for p in d.rglob("*") if p.is_file()
                 and p.name not in (TRANSMITTAL_JSON, TRANSMITTAL_MD) and p.relative_to(d).as_posix() not in t["files"]]
        errs += [f"{where}/{x}: not part of the transmittal (added by hand)" for x in extra]
    return errs
