"""Cover data of an MDL document produced by an engine: number, title, description, current revision and history.

The revision shown is the latest document_revision record; before the first issue the deliverable is marked as the draft
of its next revision (release rules, engine/core/release.py). `python -m engine doc issue` creates the revision record,
re-runs the producing engine (document.produced_by) so the cover shows the issued revision, and freezes the document's
files in internal_deliveries/ with a transmittal."""
from __future__ import annotations

from . import release


def state(store, no: str) -> dict:
    doc = store.get("document", no) or {"id": no, "title": no}
    types = {t["id"]: t for t in store.records("doc_type")}
    revs = sorted((r for r in store.records("document_revision") if r["document"] == no),
                  key=lambda r: (r["issue_date"], r.get("_meta", {}).get("created_at", "")))
    if revs:
        last = revs[-1]
        status = f"Rev {last['revision']} - {last['purpose']}, issued {last['issue_date']}"
        rev, purpose = last["revision"], last["purpose"]
    else:
        st = release.states(store).get(no) or release.DocState(no)
        purpose = release.next_purpose(doc, st, types) or "IFR"
        rev = release.next_rev(st, purpose)
        status = f"Rev {rev} - {purpose}, draft (not issued)"
    hist = [[r["revision"], r["purpose"], r["issue_date"], r.get("description") or "", r.get("prepared_by") or "",
             r.get("checked_by") or "", r.get("approved_by") or ""] for r in revs]
    return {"doc": doc, "rev": rev, "purpose": purpose, "status": status, "history": hist,
            "type": types.get(doc.get("type_code"), {}), "issued": bool(revs)}


def word(ctx, no: str, engine, landscape: bool = False):
    """A Word document (wordkit.Doc) with the cover block; the caller adds the body."""
    from .wordkit import Doc
    s = ctx.store
    c = state(s, no)
    d0 = c["doc"]
    proj = ctx.project_record()
    d = Doc(ctx.template("docx", "datasheet_base.docx"), f"{proj.get('name', '')} | {no} | Rev {c['rev']}",
            f"engine {engine.name} v{engine.version} | data {ctx.stamp['inputs_hash']} | generated "
            f"{ctx.stamp['generated_at'][:10]} - generated from the project database; do not edit", landscape=landscape)
    d.title(f"{proj.get('name', '')}\n{d0['title']}")
    party = (s.get("party", "IEPC") or {}).get("name", "IEPC") if d0.get("originator", "EPC") == "EPC" else d0.get("originator")
    rows = [("Document number", no)] + ([("Description", d0["description"])] if d0.get("description") else []) + [
        ("Revision / status", c["status"]), ("Originator", party),
        ("Discipline / type", f"{(d0.get('discipline') or '-').replace('_', ' ')} / {d0.get('type_code', '-')} "
                              f"{c['type'].get('title', '')}".strip()),
        ("Review class", (d0.get("review") or c["type"].get("review") or "-") + (" (Basic Design Package)" if d0.get("bdp") else ""))]
    if d0.get("system"):
        rows.append(("System", f"{d0['system']} {(s.get('system', d0['system']) or {}).get('title', '')}"))
    if d0.get("mr"):
        rows.append(("Procurement package", f"{d0['mr']} {(s.get('mr', d0['mr']) or {}).get('title', '')}"))
    if d0.get("basis_refs"):
        rows.append(("Basis", ", ".join(d0["basis_refs"])))
    tb = d.table(None, [list(r) for r in rows], [4.5, d.width_cm - 4.5], size=8)
    for r in tb.rows:
        r.cells[0].paragraphs[0].runs[0].bold = True
    if c["history"]:
        d.table(["Rev", "Purpose", "Date", "Description", "Prepared", "Checked", "Approved"], c["history"],
                [1.0, 1.4, 2.0, d.width_cm - 10.4, 2.0, 2.0, 2.0], size=7)
    return d


def xlsx_cover(wb, ctx, no: str, engine):
    """First sheet 'Cover' of a workbook deliverable."""
    from openpyxl.styles import Alignment, Font
    s = ctx.store
    c = state(s, no)
    d0 = c["doc"]
    ws = wb.create_sheet("Cover", 0)
    ws["A1"] = ctx.project_record().get("name", "")
    ws["A1"].font = Font(bold=True, size=12)
    ws["A2"] = d0["title"]
    ws["A2"].font = Font(bold=True, size=16)
    rows = [("Document number", no), ("Description", d0.get("description") or ""), ("Revision / status", c["status"]),
            ("Originator", d0.get("originator", "EPC")), ("Discipline", (d0.get("discipline") or "").replace("_", " ")),
            ("Generated by", f"engine {engine.name} v{engine.version} | data {ctx.stamp['inputs_hash']} | "
                             f"{ctx.stamp['generated_at'][:10]} - generated from the project database; do not edit")]
    for i, (k, v) in enumerate(rows, 4):
        ws.cell(i, 1, k).font = Font(bold=True)
        ws.cell(i, 2, v).alignment = Alignment(wrap_text=True)
    r0 = 4 + len(rows) + 1
    if c["history"]:
        for j, h in enumerate(["Rev", "Purpose", "Date", "Description", "Prepared", "Checked", "Approved"], 1):
            ws.cell(r0, j, h).font = Font(bold=True)
        for i, h in enumerate(c["history"], r0 + 1):
            for j, v in enumerate(h, 1):
                ws.cell(i, j, v)
    ws.column_dimensions["A"].width, ws.column_dimensions["B"].width = 22, 90
    return ws
