"""3D plant model (IFC4) from equipment + piping records - for AVEVA E3D (IFC import), Navisworks,
Plant 3D (reference/attach via Navisworks or IFC-capable viewers) and any IFC viewer.

Geometry fidelity (stated in every element's Alpilla_Model pset):
  equipment      envelope from shape + dimensions (box / vertical / horizontal cylinder)   -> "envelope"
  pipe, elbow    true OD and wall (ASME B36.10M), elbow as circular arc                    -> "exact"
  reducer        tapered, true end ODs                                                     -> "exact"
  valve, flange, support, instrument   simple symbolic solids (sizes are not design data)  -> "symbolic"
Each line is an IfcDistributionSystem grouping its components.
"""
from __future__ import annotations

import math

from ..core import piping
from ..core.runner import Context, Engine

EQUIP_CLASS = [("pump", "IfcPump"), ("compressor", "IfcCompressor"), ("fan", "IfcFan"), ("tank", "IfcTank"),
               ("vessel", "IfcTank"), ("drum", "IfcTank"), ("heat exchanger", "IfcHeatExchanger"),
               ("exchanger", "IfcHeatExchanger"), ("cooler", "IfcHeatExchanger"), ("filter", "IfcFilter"),
               ("transformer", "IfcTransformer"), ("generator", "IfcElectricGenerator"), ("motor", "IfcElectricMotor")]


def _unit(v):
    l = math.sqrt(sum(x * x for x in v))
    return [x / l for x in v] if l else [0.0, 0.0, 1.0]


def _perp(d):
    ref = [0.0, 0.0, 1.0] if abs(d[2]) < 0.9 else [1.0, 0.0, 0.0]
    x = [ref[1] * d[2] - ref[2] * d[1], ref[2] * d[0] - ref[0] * d[2], ref[0] * d[1] - ref[1] * d[0]]
    return _unit(x)


class ModelIFC(Engine):
    name = "model_ifc"
    title = "3D plant model IFC4 (equipment envelopes, routed piping) for E3D / Navisworks / viewers"
    version = "1.0.0"
    inputs = ["project", "system", "equipment", "line", "pipe_component", "pipe_spec", "pipe_size", "instrument"]
    formats = ["ifc"]

    def run(self, ctx: Context):
        import ifcopenshell
        import ifcopenshell.api.aggregate
        import ifcopenshell.api.context
        import ifcopenshell.api.geometry
        import ifcopenshell.api.project
        import ifcopenshell.api.pset
        import ifcopenshell.api.root
        import ifcopenshell.api.spatial
        import ifcopenshell.api.system
        import ifcopenshell.api.unit
        api = ifcopenshell.api
        s = ctx.store
        prj = ctx.project_record()
        f = api.project.create_file(version="IFC4")
        self.f = f
        project = api.root.create_entity(f, ifc_class="IfcProject", name=prj.get("name", prj["id"]))
        project.LongName = f"{prj['id']} - generated by {self.name} v{self.version} from data {ctx.stamp['inputs_hash']}"
        api.unit.assign_unit(f)
        model = api.context.add_context(f, context_type="Model")
        self.body = api.context.add_context(f, context_type="Model", context_identifier="Body",
                                            target_view="MODEL_VIEW", parent=model)
        site = api.root.create_entity(f, ifc_class="IfcSite", name=prj.get("location") or "Site")
        building = api.root.create_entity(f, ifc_class="IfcBuilding", name=prj.get("name", prj["id"]))
        storey = api.root.create_entity(f, ifc_class="IfcBuildingStorey", name="Plant")
        api.aggregate.assign_object(f, products=[site], relating_object=project)
        api.aggregate.assign_object(f, products=[building], relating_object=site)
        api.aggregate.assign_object(f, products=[storey], relating_object=building)
        for e in (site, building, storey):
            e.ObjectPlacement = self.placement([0, 0, 0])
        elements = []
        n_equipment = n_comp = 0

        for eq in s.records("equipment"):
            if eq.get("status") == "deleted":
                continue
            if not (eq.get("position") and eq.get("shape")):
                ctx.warnings.append(f"equipment {eq['id']}: no position/shape - not modelled")
                continue
            cls = next((c for k, c in EQUIP_CLASS if k in eq.get("equipment_type", "").lower()), "IfcBuildingElementProxy")
            el = api.root.create_entity(f, ifc_class=cls, name=eq["id"])
            el.Description = eq["description"]
            el.Tag = eq["id"]
            solid = self.equipment_solid(eq, ctx)
            if solid is None:
                continue
            el.ObjectPlacement = self.placement([0, 0, 0])
            api.geometry.assign_representation(f, product=el, representation=self.shape([solid]))
            self.pset(el, "Alpilla_Common", {"Tag": eq["id"], "System": eq["system"], "EquipmentType": eq.get("equipment_type"),
                                             "Status": eq.get("status"), "AVEVAClass": eq.get("aveva_class")})
            self.pset(el, "Alpilla_Model", {"GeometryFidelity": "envelope", "Source": "equipment record"})
            if eq.get("aveva_attrs"):
                self.pset(el, "Alpilla_AVEVA", {k: (f"{v['value']} {v['unit']}" if isinstance(v, dict) else v)
                                                for k, v in eq["aveva_attrs"].items()})
            elements.append(el)
            n_equipment += 1

        for line in s.records("line"):
            if line.get("status") == "deleted":
                continue
            comps = piping.components(s, line["id"])
            if not comps:
                continue
            props = piping.line_props(s, line)
            system = api.system.add_system(f, ifc_class="IfcDistributionSystem")
            system.Name = line["id"]
            system.Description = line["service"]
            members = []
            for c in comps:
                el = self.component(c, line, props, ctx)
                if el is None:
                    continue
                members.append(el)
                n_comp += 1
            flow = [m for m in members if m.is_a("IfcDistributionElement")]   # supports: linked by pset only
            if flow:
                api.system.assign_system(f, products=flow, system=system)
            elements += members
        if elements:
            api.spatial.assign_container(f, products=elements, relating_structure=storey)
        out = ctx.out_dir / f"{prj['id']}_plant_model.ifc"
        f.write(str(out))
        if not elements:
            ctx.warnings.append("nothing to model (no equipment with position/shape, no routed lines)")
        ctx.warnings.append(f"modelled {n_equipment} equipment item(s) and {n_comp} piping component(s)")
        return [out]

    # ---------------------------------------------------------------- helpers
    def placement(self, loc, axis=None, ref=None):
        f = self.f
        a = f.createIfcAxis2Placement3D(f.createIfcCartesianPoint([float(v) for v in loc]),
                                        f.createIfcDirection([float(v) for v in axis]) if axis else None,
                                        f.createIfcDirection([float(v) for v in ref]) if ref else None)
        return f.createIfcLocalPlacement(None, a)

    def axis(self, loc, axis=None, ref=None):
        f = self.f
        return f.createIfcAxis2Placement3D(f.createIfcCartesianPoint([float(v) for v in loc]),
                                           f.createIfcDirection([float(v) for v in axis]) if axis else None,
                                           f.createIfcDirection([float(v) for v in ref]) if ref else None)

    def shape(self, items):
        """IFC4 representation type must match the items (IfcShapeRepresentationTypes rule)."""
        advanced = ("IfcExtrudedAreaSolidTapered", "IfcSweptDiskSolid")
        if all(i.is_a("IfcExtrudedAreaSolid") and not i.is_a("IfcExtrudedAreaSolidTapered") for i in items):
            rtype = "SweptSolid"
        elif all(i.is_a() in advanced or i.is_a("IfcSweptAreaSolid") or i.is_a("IfcSweptDiskSolid") for i in items):
            rtype = "AdvancedSweptSolid"
        else:
            rtype = "SolidModel"
        return self.f.createIfcShapeRepresentation(self.body, "Body", rtype, items)

    def pset(self, el, name, props):
        import ifcopenshell.api.pset
        ps = ifcopenshell.api.pset.add_pset(self.f, product=el, name=name)
        ifcopenshell.api.pset.edit_pset(self.f, pset=ps, properties={k: v for k, v in props.items() if v is not None})

    def extrude(self, profile, start, direction, depth):
        f = self.f
        d = _unit(direction)
        return f.createIfcExtrudedAreaSolid(profile, self.axis(start, d, _perp(d)), f.createIfcDirection([0.0, 0.0, 1.0]),
                                            float(depth))

    def circle(self, r, wall=None):
        f = self.f
        p2 = f.createIfcAxis2Placement2D(f.createIfcCartesianPoint([0.0, 0.0]), None)
        if wall and 0 < wall < r:
            return f.createIfcCircleHollowProfileDef("AREA", None, p2, float(r), float(wall))
        return f.createIfcCircleProfileDef("AREA", None, p2, float(r))

    def equipment_solid(self, eq, ctx):
        f = self.f
        x, y, z = eq["position"]
        a = math.radians(eq.get("orientation") or 0)
        ref = [math.cos(a), math.sin(a), 0.0]
        shp = eq["shape"]
        need = {"box": ("length", "width", "height"), "vertical_cylinder": ("diameter", "height"),
                "horizontal_cylinder": ("diameter", "length")}[shp]
        missing = [k for k in need if not eq.get(k)]
        if missing:
            ctx.warnings.append(f"equipment {eq['id']}: {shp} needs {missing} - not modelled")
            return None
        p2 = f.createIfcAxis2Placement2D(f.createIfcCartesianPoint([0.0, 0.0]), None)
        if shp == "box":
            prof = f.createIfcRectangleProfileDef("AREA", None, p2, float(eq["length"]), float(eq["width"]))
            return f.createIfcExtrudedAreaSolid(prof, self.axis([x, y, z], [0, 0, 1], ref), f.createIfcDirection([0.0, 0.0, 1.0]),
                                                float(eq["height"]))
        if shp == "vertical_cylinder":
            return f.createIfcExtrudedAreaSolid(self.circle(eq["diameter"] / 2), self.axis([x, y, z], [0, 0, 1], ref),
                                                f.createIfcDirection([0.0, 0.0, 1.0]), float(eq["height"]))
        L, D = eq["length"], eq["diameter"]
        start = [x - ref[0] * L / 2, y - ref[1] * L / 2, z + D / 2]
        return self.extrude(self.circle(D / 2), start, ref, L)

    def component(self, c, line, props, ctx):
        import ifcopenshell.api.geometry
        import ifcopenshell.api.root
        f = self.f
        s = ctx.store
        t = c["type"]
        od = piping.od_of(s, c, line)
        wall = props["wall"]
        fidelity = "exact"
        items = []
        if t == "PIPE":
            cls, ptype = "IfcPipeSegment", "RIGIDSEGMENT"
            items.append(self.extrude(self.circle(od / 2, wall), c["end1"], [b - a for a, b in zip(c["end1"], c["end2"])],
                                      piping.dist(c["end1"], c["end2"])))
        elif t in ("ELBOW", "BEND"):
            cls, ptype = "IfcPipeFitting", "BEND"
            pts = piping.arc_points(c["end1"], c["centre"], c["end2"], 12)
            poly = f.createIfcPolyline([f.createIfcCartesianPoint([float(v) for v in p]) for p in pts])
            items.append(f.createIfcSweptDiskSolid(poly, float(od / 2), float(od / 2 - wall) if wall else None, None, None))
        elif t in ("TEE", "OLET"):
            cls, ptype = "IfcPipeFitting", "JUNCTION"
            if t == "TEE":
                items.append(self.extrude(self.circle(od / 2, wall), c["end1"],
                                          [b - a for a, b in zip(c["end1"], c["end2"])], piping.dist(c["end1"], c["end2"])))
            od2 = piping.od_of(s, c, line, "dn2") or od
            items.append(self.extrude(self.circle(od2 / 2), c["centre"], [b - a for a, b in zip(c["centre"], c["branch"])],
                                      piping.dist(c["centre"], c["branch"])))
        elif t.startswith("REDUCER"):
            cls, ptype = "IfcPipeFitting", "TRANSITION"
            od2 = piping.od_of(s, c, line, "dn2")
            d = [b - a for a, b in zip(c["end1"], c["end2"])]
            ax = self.axis(c["end1"], _unit(d), _perp(_unit(d)))
            items.append(f.createIfcExtrudedAreaSolidTapered(self.circle(od / 2), ax, f.createIfcDirection([0.0, 0.0, 1.0]),
                                                             float(piping.dist(c["end1"], c["end2"])), self.circle(od2 / 2)))
        elif t in ("FLANGE", "FLANGE-BLIND", "GASKET", "CAP"):
            cls, ptype, fidelity = "IfcPipeFitting", "CONNECTOR", "symbolic"
            e2 = c.get("end2") or [a + b for a, b in zip(c["end1"], [0, 0, 20])]
            items.append(self.extrude(self.circle(od * 0.8), c["end1"], [b - a for a, b in zip(c["end1"], e2)],
                                      max(10.0, piping.dist(c["end1"], e2))))
        elif t in ("VALVE", "INSTRUMENT"):
            cls, ptype = ("IfcValve", "ISOLATING") if t == "VALVE" else ("IfcFlowInstrument", "NOTDEFINED")
            fidelity = "symbolic"
            if t == "VALVE" and c.get("valve_type") == "check":
                ptype = "CHECK"
            elif t == "VALVE" and c.get("valve_type") == "control":
                ptype = "REGULATING"
            elif t == "VALVE" and c.get("valve_type") == "relief":
                ptype = "SAFETYCUTOFF"
            d = [b - a for a, b in zip(c["end1"], c["end2"])]
            items.append(self.extrude(self.circle(od * 0.65), c["end1"], d, piping.dist(c["end1"], c["end2"])))
            mid = [(a + b) / 2 for a, b in zip(c["end1"], c["end2"])]
            items.append(self.extrude(self.circle(od * 0.12), mid, _perp(_unit(d)) if abs(_unit(d)[2]) > 0.9 else [0, 0, 1], od * 1.4))
        elif t == "SUPPORT":
            cls, ptype, fidelity = "IfcBuildingElementProxy", None, "symbolic"
            p2 = f.createIfcAxis2Placement2D(f.createIfcCartesianPoint([0.0, 0.0]), None)
            prof = f.createIfcRectangleProfileDef("AREA", None, p2, float(od * 1.2), float(od * 1.2))
            base = [c["end1"][0], c["end1"][1], c["end1"][2] - od / 2 - 150]
            items.append(f.createIfcExtrudedAreaSolid(prof, self.axis(base, [0, 0, 1], [1, 0, 0]),
                                                      f.createIfcDirection([0.0, 0.0, 1.0]), 150.0))
        else:
            ctx.warnings.append(f"{line['id']} seq {c['seq']}: {t} not modelled")
            return None
        el = ifcopenshell.api.root.create_entity(f, ifc_class=cls, name=c.get("tag") or f"{line['id']}-{c['seq']}",
                                                 predefined_type=ptype)
        el.ObjectPlacement = self.placement([0, 0, 0])
        el.Tag = c.get("tag")
        ifcopenshell.api.geometry.assign_representation(f, product=el, representation=self.shape(items))
        self.pset(el, "Alpilla_Common", {"Line": line["id"], "Seq": c["seq"], "ComponentType": t,
                                         "NominalSize": c.get("dn") or line["dn"], "PipingSpec": line["spec"],
                                         "DesignPressure_barg": line["design_pressure"],
                                         "DesignTemperature_degC": line["design_temperature"],
                                         "Insulation": line.get("insulation"), "ValveType": c.get("valve_type"),
                                         "SupportType": c.get("support_type")})
        self.pset(el, "Alpilla_Model", {"GeometryFidelity": fidelity, "WallThickness_mm": wall,
                                        "WallSource": props["wall_source"]})
        return el


ENGINE = ModelIFC()
